server:
    port: 8080

spring:
    application:
        name: spring-sandbox

    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1234

    jpa:
        hibernate:
            ddl-auto: update

security:
    jwt:
        secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
        expiration-time: 3600000
